apps/home/urls.py
from django.contrib import admin
from django.urls import path

# Views
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.login, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

daras/urls.py
from django.contrib import admin
from django.urls import path, include

# Serve MEDIA in development mode
from django.conf.urls.static import static
from django.conf import settings

# Views

urlpatterns = [
    path('', include('apps.home.urls', namespace='home')),
    path('', include('apps.budget.urls', namespace='budget')),
    path('api/', include('apps.api_rest.urls', namespace='api_rest')),

    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/home/models.py
from django.db import models

# Models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    """ Profile Model """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_client = models.BooleanField(default=True)
    image = models.ImageField(blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=10 ,blank=True, null=True)
    
    def __str__(self):
        return 'Perfil de {}'.format(self.user)
    
    class Meta:
        verbose_name = 'perfil de usuario'
        verbose_name_plural = 'perfiles de usuario'
    

apps/home/forms.py
# Forms
from django import forms
from django.contrib.auth.forms import UserCreationForm

# Models
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm, forms.ModelForm):
    username = forms.EmailField(max_length=50, required=True)

    class Meta:
        model = User
        fields = ('username','first_name','last_name','password1','password2')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Las contraseñas no coinciden')
        return password2

    

apps/home/views.py
# Django
from django.contrib import messages
from django.contrib.messages import get_messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as LoginUser, logout as LogoutUser

# Decorators
from django.contrib.auth.decorators import login_required

# Forms
from .forms import SignUpForm
from django import forms

# Models
from .models import Profile
from django.contrib.auth.models import User

# Create your views here.


@login_required
def logout(request):
    LogoutUser(request)
    return redirect('home:login')


def login(request):
    """ Login view """

    storage = get_messages(request)
    messages = []
    for m in storage:
        messages.append(m.message)
        print("Mensaje: ", m.message)

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user:
            LoginUser(request, user)
            print(username + ' y ' + password)
            return redirect('budget:panel')
        else:
            return render(
                request=request,
                template_name='home/login.html',
                context={
                    "error": "Verifique sus datos de acceso"
                })

    return render(
        request=request,
        template_name='home/login.html',
        context={
            'messages': messages
        })


def signup(request):
    """ Signup client users"""
    form = SignUpForm()

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            name = data['first_name']
            last_name = data['last_name']
            email = data['username']
            password1 = data['password1']
            password2 = data['password2']
            user = User.objects.create_user(
                username=email, email=email, password=password1)
            user.first_name = name
            user.last_name = last_name
            user.save()
            p = Profile(user=user)
            # is_client is True by defualt
            p.save()

            messages.success(request, 'Registro exitoso.')
            return redirect('home:login')

    return render(request, 'home/signup.html', {
        'form': form,
    })

templates/home/login-signup-base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Toastr CSS -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    {% block title %}  
    {% endblock title %}

    <style>

        #section1{
            position: relative;
            background-image: url('{% static "home/img/soldador.jpg" %}');
            background-position: right;
            background-size: cover;
            overflow: hidden;
            background-repeat: no-repeat;
        }
    
        #curve {
            position: absolute;
            left: 0;
            height: 100%; 
        }
    </style>


</head>
<body>

    <section class="row no-gutters min-vh-100 p-0">
        <div id="section1" class="col-lg-4 bg-primary-3 d-flex justify-content-end">
            <!-- <img src="assets/article-9.jpg" class="" alt=""> -->
            <div class="divider divider-vertical d-none d-lg-block">
                <svg id="curve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100"
                    preserveAspectRatio="none" width="100%" height="100%" version="1.1" class="injected-svg"
                    data-src="{% static 'home/img/divider-vertical-1.svg' %}">
                    <!-- data-src="assets/divider-vertical-1.svg"> -->
                    <path
                        d="M0,0 L100,0 L100,100 L0,100 C66.6666667,83.3333333 100,66.6666667 100,50 C100,33.3333333 66.6666667,16.6666667 0,0 Z"
                        fill="white"></path>
                </svg>
            </div>
        </div>
        <div class="col px-5 position-relative d-flex align-items-center">
            <div class="row justify-content-center w-100">
                <div class="col-md-8 col-lg-7 col-xl-6">
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </div>
        </div>
    </section>
    {% block scripts %}
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <!-- Popper -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
    <!-- Bootstrap - Javascript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
    
    {% endblock scripts %}
</body>
</html>

templates/home/login.html
{% extends "home/login-signup-base.html" %}
{% load static %}
{% block title %}
<title>
    Iniciar sesión - DARAS
</title>
{% endblock title %}

{% block content %}
<div class="text-center mb-4">
    <img src="{% static 'home/img/logo-daras.png' %}" height="70" alt="">
    <h3 class="mb-1">Iniciar Sesión</h3>
    {% if error %}
    <div class="alert alert-danger">
        {{error}}
    </div>
    {% endif %}
    <!-- {% if form.errors %}
        <ul>
            {% for e in form.errors %}
            <li>
                {{e}}
            </li>
            {% endfor %}
        </ul>
    {% endif %} -->
    <!-- <span>No credit card required</span> -->
</div>
<form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input type="email" name="username" placeholder="Correo electrónico" class="form-control" autofocus>
    </div>

    <div class="form-group">
        <input type="password" name="password" placeholder="Contraseña"
            class="form-control {% if form.password.errors %}is-invalid{% endif %}">
        <div class="invalid-feedback">
            {% for error in form.password.errors  %}
            {{error}}
            {% endfor %}
        </div>
    </div>

    <div class="form-group text-center">
        <button class="btn-block btn btn-primary" type="submit">Iniciar sesión</button>
        <small>
            ¿Aún no tienes una cuenta?
            <a href="{% url 'home:signup' %}">Registrarme</a>
        </small>
    </div>

</form>

{% endblock content %}
{% block scripts %}
{{block.super}}
<!-- Toastr -->
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script>
    
    $(document).ready(function () {
        /* Messages Notifications */
        "{% if messages %}"
        "{% for m in messages %}"
        toastr.success('{{ m }}');
        "{% endfor %}"
        "{% endif %}"
        /* end of Messages Notifications */
    })
</script>
{% endblock scripts %}

templates/home/signup.html
{% extends "home/login-signup-base.html" %}
{% load static %}

{% block title %}
<title>Registro - DARAS</title>
{% endblock title %}

{% block content %}
<div class="text-center mb-4">
    <img src="{% static 'home/img/logo-daras.png' %}" height="70" class="animated flash infinite">
    <h3 class="mb-1">Crear cuenta</h3>
    <!-- {% if form.errors %}
        <ul>
            {% for e in form.errors %}
            <li>
                {{e}}
            </li>
            {% endfor %}
        </ul>
    {% endif %} -->
    <!-- <span>No credit card required</span> -->


</div>
<form action="" method="post">
    
    {% csrf_token %}
    <div class="form-group">
        <input type="text" class="form-control" name="first_name" placeholder="Nombres">
        <input type="text" class="mt-1 form-control" name="last_name" placeholder="Apellidos">
    </div>

    <div class="form-group">
        <small class="text-muted" for="">Año de nacimiento</small>
        <input type="date" class="form-control" name="birthday"> 
    </div>

    <div class="form-group">
        <small class="text-muted" for="">Correo electrónico</small>

        <input type="email" name="username" placeholder="Correo electrónico"
            class="form-control {% if form.username.errors %}is-invalid{% endif %}">
        <div class="invalid-feedback">
            {% for error in form.username.errors  %}
            {{error}}
            {% endfor %}
        </div>
    </div>

    <div class="form-group">
        <small class="text-muted">Contraseña</small>
        <input type="password" name="password1" placeholder="Contraseña" class="form-control">
        <small class="text-muted">Mínimo 8 caracteres</small>
        <input type="password" name="password2" placeholder="Repetir contraseña"
            class="mt-1 form-control {% if form.password2.errors %}is-invalid{% endif %}">
        <div class="invalid-feedback">
            {% for error in form.password2.errors  %}
            {{error}}
            {% endfor %}
        </div>
    </div>

    <div class="form-group text-center">
        <button class="btn-block btn btn-primary" type="submit">Registrarme</button>
        <small>
            ¿Ya tienes una cuenta? <a href="{% url 'home:login' %}">Iniciar sesión</a>
        </small>
    </div>
    <!-- <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="signup-agree">
        <label class="custom-control-label text-small text-muted" for="signup-agree">I agree to the
            <a href="#">Terms &amp;
                Conditions</a>
        </label>
    </div> -->
    <!-- <hr>
    <div class="text-center text-small text-muted">
        <span>Already have an account yet? <a href="#">Sign In</a>
        </span>
    </div> -->
</form>
{% endblock content %}