apps/budget/urls.py
from django.contrib import admin
from django.urls import path

# Views
from . import views

app_name = 'budget'
urlpatterns = [
    path('panel/', views.panel, name='panel' ),
    path('panel/crear/usuario/', views.createDarasUser, name='create-daras-user'),
    path('panel/editar/usuario/<int:user_id>', views.editDarasUser, name='edit-daras-user'),
    path('panel/crear/cliente/', views.createClient, name='create-client'),
    path('panel/crear/actividad/', views.createBudgetActivity, name='create-activity'),
    path('panel/ver/actividades/', views.listActivities, name='list-activities'),
    path('panel/ver/clientes/', views.listClient, name='list-client'),
    path('panel/ver/usuarios/', views.listDarasUsers, name='list-users'),
    path('panel/ver/presupuestos/', views.listBudgets, name='list-budgets' ),
    path('panel/crear/presupuesto/', views.createBudget, name='create-budget' ),
    path('panel/completar/presupuesto/<int:pk>', views.fillBudget, name='fill-budget'),
    path('panel/presupuesto/<int:budget_pk>/detalle', views.budgetDetail, name='budget-detail' ),
    path('panel/presupuesto/<slug:slug>/item/<slug:slug_item>/', views.editBudgetItem, name='edit-item' ),
    path('panel/presupuesto/<int:budget_pk>/item/<int:item_pk>/subitem/<int:subitem_pk>/apu/', views.editBudgetSubItem, name='edit-subitem'),
    path('panel/presupuesto/<int:budget_pk>/item/<int:item_pk>/actualizar/subitem/<int:subitem_pk>/', views.updateBudgetSubitem, name='update-subitem'),
    path('panel/preview/presupuesto/<int:budget_pk>/',views.PreviewBudget, name="preview-budget"),
    path('panel/preview/presupuesto/<int:budget_pk>/item/<int:item_pk>/subitem/<int:subitem_pk>/', views.PreviewAPU, name='preview-apu'),
    path('panel/admin/', views.PanelAdmin, name='administration' ),

]

apps/home/urls.py
from django.contrib import admin
from django.urls import path

# Views
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.login, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

daras/urls.py
from django.contrib import admin
from django.urls import path, include

# Serve MEDIA in development mode
from django.conf.urls.static import static
from django.conf import settings

# Views

urlpatterns = [
    path('', include('apps.home.urls', namespace='home')),
    path('', include('apps.budget.urls', namespace='budget')),
    path('api/', include('apps.api_rest.urls', namespace='api_rest')),

    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/budget/forms.py
# Forms
from django import forms
from django.contrib.auth.forms import UserCreationForm

# Models
from .models import *
from django.contrib.auth.models import User

class CreateActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ('title','unit','unit_value','category','service')

class CreateDarasUserForm(UserCreationForm, forms.ModelForm):
    username = forms.EmailField(max_length=50, required=True)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Las contraseñas no coinciden')
        return password2
        
    class Meta:
        model = User
        fields = ('username','first_name','last_name','password1','password2')

class EditDarasUserForm(UserCreationForm, forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','first_name','last_name','password1')

class CreateClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('nit', 'name', 'country', 'state', 'city', 'address')

class CreateBudgetForm(forms.ModelForm):
    """ Create Budget form """

    class Meta:
        model = Budget
        fields = (
            'typeOf',
            'client',
            'risk',
            'time',
            'service',
            'iva_option',
            'iva',
        )

class FillBudgetForm(forms.ModelForm):
    """ Fill budget form """

    class Meta:
        model = Budget
        fields = (
            'consecutive',
            'client',
            'subject',
            'delivery_time',
            'rev_number',
            'aiu_over',
            'comment',
            'utility_percentage',
            'incidentals_percentaje',
            'administration_percentage',
            'iva_option',
        )

class BudgetSubItemForm(forms.ModelForm):
    """ Budget items form"""

    def __init__(self, *args, **kwargs):
        super(BudgetSubItemForm, self).__init__(*args, **kwargs)
        self.fields['unit'].empty_label = "Unidades"

    class Meta:
        model = BudgetSubItem
        fields = ('description', 'unit', 'amount')

apps/budget/views.py
# Django
import tempfile
# from weasyprint import HTML
from django.template.loader import render_to_string
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse

# Decorators
from django.contrib.auth.decorators import login_required

# Forms
from .forms import *

# Models
from .models import *

# Utilities
from decimal import Decimal
from .utils import render_to_pdf
from django.utils import timezone
import json


# Create your views here.

@login_required
def createDarasUser(request):
    """ Create Daras user view """
    form = CreateDarasUserForm()
    if request.method == 'POST':
        form = CreateDarasUserForm(request.POST)
        
        if form.is_valid():
            data = form.cleaned_data
            
            username = data['username']
            password1 = data['password1']
            password2 = data['password2']

            member = User(username=username, password=password1)
            member.first_name = data['first_name']
            member.last_name = data['last_name']
            member.save()
            
            p = Profile()
            p.user = member
            p.is_client = False
            p.save()

            return redirect('budget:administration')

    return render(request, 'budget/create-user.html', {
        'form':form
    })

def editDarasUser(request,user_id):
    form = EditDarasUserForm()
    user = User.objects.get(id=user_id)

    if request.method == 'POST':
        form = EditDarasUserForm(request.POST)
        if form.is_Valid():
            data = form.cleaned_data
            u = User.objects.get(id=user_id)
            u.first_name = data['first_name']
            u.last_name = data['last_name']
            u.email = data['email']
            if data['password1'] != '':
                u.password = data['password1']
            u.save()
            return redirect('budget:administration')
    return render(request, 'budget/edit-user.html',{
        'form':form,
        'user':user,
    })

@login_required
def listDarasUsers(request):
    daras_users = Profile.objects.filter(is_client=False)
    return render(request, 'budget/list-users.html',{
        'daras_users':daras_users,
    })

@login_required
def createBudgetActivity(request):
    form = CreateActivityForm()
    services = Service.objects.filter(budget_type__slug='actividades')
    if request.method == 'POST':
        form = CreateActivityForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            a = Activity()
            a.title = data['title']
            a.unit = data['unit']
            a.unit_value = data['unit_value']
            a.service = data['service']
            a.category = data['category']
            a.save()

            return redirect('budget:administration')

    return render(request, 'budget/create-activity.html', {
        'form':form,
        'services':services,
    })

@login_required
def listActivities(request):
    activities = Activity.objects.all()

    return render(request, 'budget/list-activities.html',{
        'activities':activities,
    })

@login_required
def panel(request):
    """ Panel view """
    return render(
        request=request,
        template_name='budget/index.html'
    )

@login_required
def createClient(request):
    """ Client creation view """
    form = CreateClientForm()
    if request.method == 'POST':
        form = CreateClientForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            c = Client()
            c.nit = data['nit']
            c.name = data['name']
            c.country = data['country']
            c.state = data['state']
            c.city = data['city']
            c.address = data['address']
            c.save()
            return redirect('budget:panel')

    return render(
        request=request,
        template_name='budget/create-client.html',
        context={
            'form': form
        })

@login_required
def listClient(request):
    """ List clients """

    clients = Client.objects.all()
    return render(
        request=request,
        template_name='budget/list-clients.html', 
        context= 
        {
            'clients':clients,
        })

@login_required
def listBudgets(request):

    # Only render purposes
    form = CreateBudgetForm()

    budgets = Budget.objects.all().order_by('-created')
    return render(
        request=request,
        template_name='budget/list-budgets.html',
        context={
            'budgets': budgets,
            'form': form
        }
    )

@login_required
def createBudget(request):
    """ Basic creation of budget """

    if request.method == 'POST':
        form = CreateBudgetForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            b = Budget()
            
            b.typeOf = data['typeOf']
            b.client = data['client']
            b.service = data['service']
            b.risk = data['risk']
            b.time = data['time']
            b.iva_option = data['iva_option']
            b.iva = data['iva']
            b.created_by = request.user.profile
            b.save()
            pk = b.id
            return redirect('budget:fill-budget', pk=pk)

@login_required
def fillBudget(request, pk):
    """ Fill Budget """
    budget = Budget.objects.get(id=pk)
    items = BudgetItem.objects.filter(budget=budget)
    clients = Client.objects.all()
    units = Unit.objects.all()
    form = FillBudgetForm()
    activities = Activity.objects.filter(service=budget.service)
    if request.method == "POST":
        form = FillBudgetForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            b = budget
            b.consecutive = data['consecutive']
            b.client = data['client']
            b.subject = data['subject']
            b.delivery_time = data['delivery_time']
            b.rev_number = data['rev_number']
            b.aiu_over = data['aiu_over']
            b.iva_option = data['iva_option']
            b.comment = data['comment']
            b.utility_percentage = data['utility_percentage']
            b.incidentals_percentaje = data['incidentals_percentaje']
            b.administration_percentage = data['administration_percentage']
            b.save()

            return redirect('budget:budget-detail', budget_pk=pk)

    return render(
        request=request,
        template_name='budget/fill-budget.html',
        context={
            'clients': clients,
            'units': units,
            'budget': budget,
            'items': items,
            'activities':activities,
            'form': form,
        }
    )

@login_required
def budgetDetail(request, budget_pk):
    """ Budget summary before edit items """

    budget = Budget.objects.get(id=budget_pk)
    items = BudgetItem.objects.filter(budget=budget)

    return render(
        request=request,
        template_name='budget/budget-detail.html',
        context={
            'budget': budget,
            'items': items,
        }
    )

@login_required
def editBudgetItem(request, slug, slug_item):
    """ Add specific activites to each activity """

    budget = get_object_or_404(Budget, slug=slug)
    item = get_object_or_404(BudgetItem, slug=slug_item)
    subitems = BudgetSubItem.objects.filter(budget=budget, item=item)

    if request.method == 'POST':

        descriptions = request.POST.getlist('description')
        units = request.POST.getlist('unit')
        amounts = request.POST.getlist('amount')
        unit_value = request.POST.getlist('value')

        if descriptions and units and amounts:
            for d, u, a, v in zip(descriptions, units, amounts, unit_value):
                S = BudgetSubItem()
                S.budget = budget
                S.item = item
                S.description = d
                aux = get_object_or_404(Unit, id=u)
                S.unit = aux
                S.amount = a
                # S.unit_value = v
                S.save()
            return redirect('budget:budget-detail', slug=slug)

    return render(
        request=request,
        template_name='budget/edit-item.html',
        context={
            'budget': budget,
            'item': item,
            'subitems': subitems,
        }
    )

@login_required
def editBudgetSubItem(request, budget_pk, item_pk, subitem_pk):
    """ Create APU for specific activity """

    budget = get_object_or_404(Budget, id=budget_pk)
    item = get_object_or_404(BudgetItem, id=item_pk)
    subitem = get_object_or_404(BudgetSubItem, id=subitem_pk)
    servicios = Service.objects.all()
    wfJson = []
    matJson = []
    equipJson = []
    
    if budget.service.slug == 'integral':
        # Building Workforce optgroups for select element (HTML)
        for i in range(len(servicios)):
            q = Workforce.objects.filter(service=servicios[i]).exists()
            if q:
                w = Workforce.objects.filter(service=servicios[i])
            else:
                # Avoid add 'Integral' label in json and select element (HTML)
                break

            aux = {
                "{}".format(servicios[i].name):list()
            }
            wfJson.append(aux)
            for j in w:
                aux2 = {
                    'id':'{}'.format(j.id),
                    'name':'{}'.format(j.name)
                }
                aux[servicios[i].name].append(aux2)
        wfJson = json.dumps(wfJson,ensure_ascii=False)
        # Building Material optgroups for select element (HTML)
        for i in range(len(servicios)):
            q = Material.objects.filter(service=servicios[i]).exists()
            if q:
                m = Material.objects.filter(service=servicios[i])
            else:
                # Avoid add 'Integral' label in json and select element (HTML)
                break
            aux = {

templates/budget/parts/footer.html
<footer class="page-footer text-center font-small primary-color-dark darken-2 mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
        <a class="btn btn-outline-white" href="#" target="_blank" role="button">
            Contacto <i class="fas fa-comment ml-2"></i>
        </a>
        <a class="btn btn-outline-white" href="#" target="_blank" role="button">
            Reportar fallo <i class="fas fa-bug ml-2"></i>
        </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
        <a href="https://www.facebook.com/Daras-Ingenieria-SAS-304072663609185/?_rdc=1&_rdr" target="_blank">
            <i class="fab fa-facebook-f mr-3"></i>
        </a>

        <!-- <a href="https://twitter.com/MDBootstrap" target="_blank">
            <i class="fab fa-twitter mr-3"></i>
        </a> -->

        <a href="#" target="_blank">
            <i class="fab fa-youtube mr-3"></i>
        </a>

        <a href="#" target="_blank">
            <i class="fab fa-instagram mr-3"></i>
        </a>

        <!-- <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
            <i class="fab fa-google-plus mr-3"></i>
        </a> -->

        <!-- <a href="https://dribbble.com/mdbootstrap" target="_blank">
            <i class="fab fa-dribbble mr-3"></i>
        </a> -->

        <!-- <a href="https://pinterest.com/mdbootstrap" target="_blank">
            <i class="fab fa-pinterest mr-3"></i>
        </a> -->

        <!-- <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
            <i class="fab fa-github mr-3"></i>
        </a> -->

        <!-- <a href="http://codepen.io/mdbootstrap/" target="_blank">
            <i class="fab fa-codepen mr-3"></i>
        </a> -->
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
        <p>Hecho con 💚 por DARAS  </p>
        © {% now "Y" %} Copyright:
        <a href="https://daras.com.co/" target="_blank"> Daras.com.co </a>
    </div>
    <!--/.Copyright-->
    
</footer>

templates/budget/parts/header.html
{% load static %}

<!--Main Navigation-->
<header>

    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
      <div class="container-fluid">

        <!-- Brand -->
        <!-- <a class="navbar-brand waves-effect" href="https://mdbootstrap.com/docs/jquery/" target="_blank">
          <strong class="blue-text">MDB</strong>
        </a> -->

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

          <!-- Left -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link waves-effect" href="#">Inicio
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="#" target="_blank">Quiénes somos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="#" target="_blank">Descargas</a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="#" target="_blank">Contacto</a>
            </li>
          </ul>

          <!-- Right -->
          <ul class="navbar-nav nav-flex-icons">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    {% if not request.user.first_name %}
                        Usuario
                    {% else %}
                        {{request.user.first_name}}
                    {% endif %}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Inicio</a>
                    <a class="dropdown-item" href="{% url 'budget:panel' %}">Panel</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'home:logout' %}">Cerrar sesión</a>
                </div>
            </li>
            <li class="nav-item">
              <a href="https://www.facebook.com/Daras-Ingenieria-SAS-304072663609185/?_rdc=1&_rdr" class="nav-link waves-effect" target="_blank">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link waves-effect" target="_blank">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <!-- <li class="nav-item">
              <a href="https://github.com/mdbootstrap/bootstrap-material-design" class="nav-link border border-light rounded waves-effect"
                target="_blank">
                <i class="fab fa-github mr-2"></i>MDB GitHub
              </a>
            </li> -->
          </ul>

        </div>

      </div>
    </nav>
    <!-- Navbar -->

    <!-- Sidebar -->
    <div id="sidebar" class="sidebar-fixed position-fixed">

      <a class="logo-wrapper waves-effect">
        <!-- <img src="https://mdbootstrap.com/img/logo/mdb-email.png" class="img-fluid" alt=""> -->
        <img src="{% static 'home/img/logo-daras.png' %}" class="img-fluid" alt="" style="mix-blend-mode: multiply;">
      </a>

      <div class="list-group list-group-flush">
        <a id="btnSidebarPanel" href="{% url 'budget:panel' %}" class="list-group-item list-group-item-action waves-effect">
          <i class="fas fa-chart-pie mr-3"></i> Dashboard
        </a>
        
        <a id="btnSidebarBudget" href="{% url 'budget:list-budgets' %}" class="list-group-item list-group-item-action waves-effect">
          <i class="fas fa-money-bill-alt mr-3"></i> Presupuestos
        </a>
        <a id="btnSidebarAdmin" href="{% url 'budget:administration' %}" class="list-group-item list-group-item-action waves-effect">
          <i class="fas fa-tools mr-3"></i> Administración
        </a>
        
        <!-- <a href="#" class="list-group-item list-group-item-action waves-effect">
          <i class="fas fa-table mr-3"></i>Tables</a> -->
        <!-- <a href="#" class="list-group-item list-group-item-action waves-effect">
          <i class="fas fa-map mr-3"></i>Maps</a> -->
      </div>

    </div>
    <!-- Sidebar -->

</header>
  <!--Main Navigation-->