apps/api_rest/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'units', views.UnitViewSet, basename='units')
router.register(r'services', views.ServicesViewSet, basename='services')
router.register(r'activityCategories', views.ActivityCategoriesViewSet, basename='activityCategories')
router.register(r'materials', views.MaterialViewSet, basename='materials')
router.register(r'equipment', views.EquipmentViewSet, basename='equipment')
router.register(r'transports', views.TransportViewSet, basename='transports')
router.register(r'secures', views.SecureViewSet, basename='secures')
router.register(r'workforce', views.WorkforceViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
app_name = 'api_rest'
urlpatterns = [
    path('', include(router.urls)),

    # Activity
    path('administration/activity-categories/service/', views.getActivityCategory, name='activity-categories'),

    # Budget APU
    path('workforce/service/<int:service>/', views.WorkforceList.as_view(), name='workforce-service'),
    path('material/service/<int:service>/', views.MaterialList.as_view(), name='material-service'),
    path('equipment/service/<int:service>/', views.EquipmentList.as_view(), name='equipment-service'),
    path('budget/<int:budget_id>/create-item/', views.CreateBudgetItem.as_view(), name='create-item'),
    path('budget/<int:budget_pk>/del-item/', views.delBudgetItem, name='del-item'),
    path('budget/<int:budget_pk>/update/item/<int:item_pk>', views.updateBudgetItem, name='update-item'),
    path('budget/<int:budget_pk>/add-subitem/<int:budgetItem_id>', views.addBudgetSubitem, name='add-subitem'),
    path('budget/<int:budget_pk>/add-activity/<int:budgetItem_id>', views.addBudgetActivity, name='add-activity'),
    path('budget/<int:budget_pk>/update/subitem/<int:subitem_pk>', views.updateBudgetSubitem, name='update-subitem'),
    path('budget/<int:budget_pk>/del-subitem/', views.delBudgetSubitem, name='del-subitem'),
    path('budget/<slug:budget_slug>/item/<slug:item_slug>/subitems', views.BudgetSubItemList.as_view(), name='budget-subitems'),



    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

apps/budget/urls.py
from django.contrib import admin
from django.urls import path

# Views
from . import views

app_name = 'budget'
urlpatterns = [
    path('panel/', views.panel, name='panel' ),
    path('panel/crear/usuario/', views.createDarasUser, name='create-daras-user'),
    path('panel/editar/usuario/<int:user_id>', views.editDarasUser, name='edit-daras-user'),
    path('panel/crear/cliente/', views.createClient, name='create-client'),
    path('panel/crear/actividad/', views.createBudgetActivity, name='create-activity'),
    path('panel/ver/actividades/', views.listActivities, name='list-activities'),
    path('panel/ver/clientes/', views.listClient, name='list-client'),
    path('panel/ver/usuarios/', views.listDarasUsers, name='list-users'),
    path('panel/ver/presupuestos/', views.listBudgets, name='list-budgets' ),
    path('panel/crear/presupuesto/', views.createBudget, name='create-budget' ),
    path('panel/completar/presupuesto/<int:pk>', views.fillBudget, name='fill-budget'),
    path('panel/presupuesto/<int:budget_pk>/detalle', views.budgetDetail, name='budget-detail' ),
    path('panel/presupuesto/<slug:slug>/item/<slug:slug_item>/', views.editBudgetItem, name='edit-item' ),
    path('panel/presupuesto/<int:budget_pk>/item/<int:item_pk>/subitem/<int:subitem_pk>/apu/', views.editBudgetSubItem, name='edit-subitem'),
    path('panel/presupuesto/<int:budget_pk>/item/<int:item_pk>/actualizar/subitem/<int:subitem_pk>/', views.updateBudgetSubitem, name='update-subitem'),
    path('panel/preview/presupuesto/<int:budget_pk>/',views.PreviewBudget, name="preview-budget"),
    path('panel/preview/presupuesto/<int:budget_pk>/item/<int:item_pk>/subitem/<int:subitem_pk>/', views.PreviewAPU, name='preview-apu'),
    path('panel/admin/', views.PanelAdmin, name='administration' ),

]

daras/urls.py
from django.contrib import admin
from django.urls import path, include

# Serve MEDIA in development mode
from django.conf.urls.static import static
from django.conf import settings

# Views

urlpatterns = [
    path('', include('apps.home.urls', namespace='home')),
    path('', include('apps.budget.urls', namespace='budget')),
    path('api/', include('apps.api_rest.urls', namespace='api_rest')),

    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/budget/models.py
# Models
from django.db import models
from ..home.models import Profile

# Utilities
from django.utils.text import slugify
from django.utils.timezone import now

# Signals
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Client(models.Model):
    """ Client Model """
    nit = models.CharField(max_length=20, blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=50, default="Colombia", blank=True, null=True)
    state = models.CharField(max_length=50, default="Bolívar", blank=True, null=True)
    city = models.CharField(max_length=50, default="Cartagena", blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "cliente"
        verbose_name_plural = "clientes"

    def __str__(self):
        return '{} - {}'.format(self.nit, self.name)

class BudgetType(models.Model):
    """Model definition for BudgetType."""

    title = models.CharField(max_length=50)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        verbose_name = 'tipo de presupuesto'
        verbose_name_plural = 'tipos de presupuesto'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(BudgetType, self).save(*args, **kwargs)

    def __str__(self):
        """Unicode representation of BudgetType."""
        return self.title

class Service(models.Model):
    """ Type of service Model """

    name = models.CharField(max_length=100)
    budget_type = models.ForeignKey(BudgetType, on_delete=models.CASCADE)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Service, self).save(*args, **kwargs)

    def __str__(self):
        return '{0} - {1}'.format(self.name, self.budget_type)

    class Meta:
        verbose_name = "tipo de servicio"
        verbose_name_plural = "tipos de servicio"

class Workforce(models.Model):
    """ Workforce model """
    EXPERIENCE_YEARS = [
        (None, 'Años de experiencia'),
        ('0-3', '0-3 años'),
        ('3', '3 años'),
        ('+3', '+3 años'),
        ('3-5', '3-5 años'),
        ('5', '5 años'),
        ('+5', '+5 años'),
        ('5-10', '5-10 años'),
        ('10', '10 años'),
        ('+10', '+10 años'),
    ]
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name="Nombre")
    experience_time = models.CharField(
        choices=EXPERIENCE_YEARS, max_length=20, blank=True, null=True, verbose_name="Años de experiencia")
    daily_salary = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Salario por día",
                                       help_text="ATENCIÓN: Esta cifra siempre debe terminar con dos decimales y no se colocan punto de mil o millón.")
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha de creación")
    modified = models.DateTimeField(
        auto_now=True, verbose_name="Última modificación")

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = "mano de obra"
        verbose_name_plural = "manos de obra"

class Risk(models.Model):
    """ Risk type model """
    name = models.CharField(max_length=20, verbose_name="Nombre")
    value = models.DecimalField(
        max_digits=3, decimal_places=2, verbose_name="Valor")

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = "tipo de riesgo"
        verbose_name_plural = "tipos de riesgo"

class Unit(models.Model):
    """ Units for budget APU """
    acronym = models.CharField(unique=True, max_length=10)
    name = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return '{} - {}'.format(self.acronym, self.name)

    class Meta:
        verbose_name = 'unidad'
        verbose_name_plural = 'unidades'

class Material(models.Model):
    """ Materials model """

    name = models.CharField(max_length=100)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, blank=True, null=True, default=1)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, default=2)
    daily_price = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    def save(self, *args, **kwargs):
        slug = '{0}-{1}'.format(self.name, now().strftime("%Y%m%d%H%M%S"))
        self.slug = slugify(slug)
        super(Material, self).save(*args, **kwargs)

    def __str__(self):
        return '{0} - {1}'.format(self.unit, self.name)

    class Meta:
        verbose_name = 'material'
        verbose_name_plural = 'materiales'

class Equipment(models.Model):
    """ Equipments and tools model """

    name = models.CharField(max_length=100)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, default=1)
    daily_price = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    def save(self, *args, **kwargs):
        slug = '{0}-{1}'.format(self.name, now().strftime("%Y%m%d%H%M%S"))
        self.slug = slugify(slug)
        super(Equipment, self).save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = 'equipo/herramienta'
        verbose_name_plural = 'equipos/herramientas'

class Transport(models.Model):
    """ Transport model """

    name = models.CharField(max_length=100)
    daily_price = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    def save(self, *args, **kwargs):
        slug = '{0}-{1}'.format(self.name, now().strftime("%Y%m%d%H%M%S"))
        self.slug = slugify(slug)
        super(Transport, self).save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = 'transporte'
        verbose_name_plural = 'transportes'

class Secure(models.Model):
    """ Secure and others model """

    name = models.CharField(max_length=100)
    daily_price = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    def save(self, *args, **kwargs):
        slug = '{0}-{1}'.format(self.name, now().strftime("%Y%m%d%H%M%S"))
        self.slug = slugify(slug)
        super(Secure, self).save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = 'seguro/otro'
        verbose_name_plural = 'seguros/otros'

class Budget(models.Model):
    """ Budget model """
    
    OPTIONS_IVA = [
        # (None, 'Calcular IVA con respecto a'),
        ('1', 'Subtotal'),
        ('2', 'Utilidad')
    ]
    OPTIONS_PERIOD = [
        # (None, 'Escala de tiempo'),
        ('1', 'Hora'),
        ('2', 'Día'),
        ('3', 'Mes')
    ]
    AIU_OPTIONS = [
        # (None, 'Aplicar AIU sobre'),
        ('1', 'Presupuesto'),
        ('2', 'APU'),
    ]
    
    typeOf = models.ForeignKey(BudgetType, on_delete=models.CASCADE, blank=True, null=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True, verbose_name="Cliente")
    consecutive = models.CharField(max_length=10, blank=True, null=True, verbose_name="Consecutivo")
    service = models.ForeignKey(Service, on_delete=models.CASCADE, blank=True, null=True, verbose_name="Especialidad")
    time = models.CharField(choices=OPTIONS_PERIOD, max_length=20, blank=True, null=True, default=2, verbose_name="Rango de tarifas")
    subject = models.CharField(max_length=300, blank=True, null=True, verbose_name="Objeto")
    risk = models.ForeignKey(Risk, on_delete=models.CASCADE, blank=True, null=True, verbose_name="Riesgo de la empresa")
    iva = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True, verbose_name="Porcentaje IVA")
    aiu_over = models.CharField(max_length=50,choices=AIU_OPTIONS, blank=True, null=True, verbose_name="Aplicar AIU sobre")
    rev_number = models.PositiveSmallIntegerField(blank=True, null=True, default=1, verbose_name="Numero de revisión")
    delivery_time = models.CharField(max_length=50, blank=True, null=True, verbose_name="Tiempo de entrega")
    
    comment = models.TextField(blank=True, null=True, verbose_name="Observaciones")
    administration_percentage = models.SmallIntegerField(blank=True, null=True, verbose_name="Porcentaje de administración")
    incidentals_percentaje = models.SmallIntegerField(blank=True, null=True, verbose_name="Porcentaje de imprevistos")
    utility_percentage = models.SmallIntegerField(blank=True, null=True, verbose_name="Porcentaje de utilidad")
    incidentals = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    administration = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    utility = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    
    total_direct_cost = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    total_indirect_cost = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    iva_option = models.CharField(choices=OPTIONS_IVA, max_length=50, blank=True, null=True, verbose_name="Calcular IVA sobre")

apps/budget/forms.py
# Forms
from django import forms
from django.contrib.auth.forms import UserCreationForm

# Models
from .models import *
from django.contrib.auth.models import User

class CreateActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ('title','unit','unit_value','category','service')

class CreateDarasUserForm(UserCreationForm, forms.ModelForm):
    username = forms.EmailField(max_length=50, required=True)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Las contraseñas no coinciden')
        return password2
        
    class Meta:
        model = User
        fields = ('username','first_name','last_name','password1','password2')

class EditDarasUserForm(UserCreationForm, forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','first_name','last_name','password1')

class CreateClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('nit', 'name', 'country', 'state', 'city', 'address')

class CreateBudgetForm(forms.ModelForm):
    """ Create Budget form """

    class Meta:
        model = Budget
        fields = (
            'typeOf',
            'client',
            'risk',
            'time',
            'service',
            'iva_option',
            'iva',
        )

class FillBudgetForm(forms.ModelForm):
    """ Fill budget form """

    class Meta:
        model = Budget
        fields = (
            'consecutive',
            'client',
            'subject',
            'delivery_time',
            'rev_number',
            'aiu_over',
            'comment',
            'utility_percentage',
            'incidentals_percentaje',
            'administration_percentage',
            'iva_option',
        )

class BudgetSubItemForm(forms.ModelForm):
    """ Budget items form"""

    def __init__(self, *args, **kwargs):
        super(BudgetSubItemForm, self).__init__(*args, **kwargs)
        self.fields['unit'].empty_label = "Unidades"

    class Meta:
        model = BudgetSubItem
        fields = ('description', 'unit', 'amount')

templates/budget/budget-detail.html
{% extends "budget/base.html" %}
{% load static %}
{% load humanize %}

{% block title %}
<title>Completar presupuesto - DARAS</title>
{% endblock title %}



{% block content %}

<!-- Heading -->
<div class="row">
    <div class="col-12">

        <div class="card mb-1 wow fadeIn">
        
            <!--Card content-->
            <div class="card-body d-sm-flex justify-content-between">
        
                <h6 class="mb-2 mb-sm-0 pt-1">
                    <span class="text-muted">Dashboard</span>
                    <span class="text-muted">/</span>
                    <span class="text-muted">Presupuesto</span>
                    <span class="text-muted">/</span>
                    <span>Resumen</span>
        
                </h6>
        
            </div>
        
        </div>
    </div>
</div>
<!-- Heading -->


<div class="row mt-3">
    <div class="col-12">

        <!-- Tabs -->
        <ul class="nav nav-tabs nav-justified md-tabs indigo" id="myTabJust" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" id="home-tab-just" data-toggle="tab" href="#home-just" role="tab" aria-controls="home-just"
                aria-selected="true">General</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="profile-tab-just" data-toggle="tab" href="#profile-just" role="tab" aria-controls="profile-just"
                aria-selected="false">Actividades</a>
            </li>
          </ul>
          <!-- Tabs content -->
          <div class="tab-content card pt-5" id="myTabContentJust">
            
            <!-- First tab content -->
            <div class="tab-pane fade show active" id="home-just" role="tabpanel" aria-labelledby="home-tab-just">
                <small>
                    Información general del presupuesto
                </small>
                
                <!-- Budget summary -->
                <table id="generalTable" class="table table-hover mt-4">
                    <tr>
                        <td>
                            <strong>
                                Tipo de presupuesto
                            </strong>
                        </td>
                        <td class="text-center">
                            {{budget.typeOf.title}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>
                                Numero de revisión
                            </strong>
                        </td>
                        <td class="text-center">
                            {{budget.rev_number}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>
                                Cliente
                            </strong>
                        </td>
                        <td class="text-center">
                            {{budget.client.name}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>
                                Riesgo
                            </strong>
                        </td>
                        <td class="text-center">
                            {{budget.risk}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>
                                Tipo de cobro
                            </strong>
                        </td>
                        <td class="text-center">
                            {{budget.get_time_display}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>
                                Tipo de servicio
                            </strong>
                        </td>
                        <td class="text-center">
                            {{budget.service}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>
                                Tiempo de entrega
                            </strong>
                        </td>
                        <td class="text-center">
                            {{budget.delivery_time}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>
                                Objeto
                            </strong>
                        </td>
                        <td class="text-center">
                            {{budget.subject|default_if_none:"-"}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>
                                Aplicar AIU a
                            </strong>
                        </td>
                        <td class="text-center">
                            {{budget.get_aiu_over_display}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>
                                Calcular IVA en base a
                            </strong>
                        </td>
                        <td class="text-center">
                            {{budget.get_iva_option_display}}
                        </td>
                    </tr>
                    
                </table>
                <a href="{% url 'budget:fill-budget' budget.id %}" class="btn btn-indigo">Editar</a>
                <a href="{% url 'budget:preview-budget' budget.id %}" class="btn btn-indigo">Reporte</a>


            </div>
            
            <!-- Second tab content -->
            <div class="tab-pane fade" id="profile-just" role="tabpanel" aria-labelledby="profile-tab-just">
                <!-- <h1>Actividades</h1> -->
                <small>Elige una actividad y crea su APU </small>
                <hr class="my-3">
                <!-- Budget items -->
                {% if items %}
                    <table id="itemsTable" class="table table-hover">
                        <thead>
                            <tr class="text-center">
                                <th>
                                    #
                                </th>
                                <th>
                                    Descripción
                                </th>
                                <th>
                                    Unidad
                                </th>
                                
                                {% if budget.typeOf.slug == 'apu' %}
                                <th>
                                    Duración
                                </th>
                                {% endif %}

                                <th>
                                    Cantidad
                                </th>
                                <th>
                                    Valor unitario
                                </th>
                                <th>
                                    Valor total
                                </th>
                                <th>
                                    Opciones
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for item in items %}
                            <tr style="background-color: rgba(0,0,0,.075);">
                                <td class="text-center">
                                    {{forloop.counter}}
                                </td>
                                <td colspan="7">
                                    {{item.description}}
                                </td>
                            </tr>
                            {% if item.subitems %}
                                {% for i in item.subitems.all %}
                                    <tr class="text-center">
                                        <td class="text-right">
                                            {{forloop.parentloop.counter}}.{{forloop.counter}}
                                        </td>
                                        <td class="text-left" style="width: 25%;">
                                            {{i.description}}
                                        </td>
                                        <td>
                                            {{i.unit.name}}
                                        </td>
                                        {% if budget.typeOf.slug == 'apu' %}
                                        <td>
                                            {{i.duration}}
                                        </td>
                                        {% endif %}
                                        <td>
                                            {{i.amount}}
                                        </td>
                                        <td>
                                            {{i.unit_value|default_if_none:'-'|intcomma}}
                                        </td>
                                        <td>
                                            {{i.total_value|default_if_none:'-'|intcomma}}
                                        </td>

                                        <td class="d-flex justify-content-around">
                                            <a href="{% url 'budget:edit-subitem' budget.id item.id i.id %}">
                                                <i class="far fa-edit"></i>
                                            </a>
                                            {% if i.apu_exists %}
                                                <a href="{% url 'budget:preview-apu' budget.id item.id i.id %}">
                                                    <i class="far fa-eye"></i>
                                                </a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                {% endif %}

                <hr>
            </div>
    
          </div>
    </div>
</div>

{% endblock content %}
{% block scripts %}
{{block.super}}
<!-- When Document is ready -->
<script>
    $(document).ready(function () {
        /* Highlight current sidebar item */
        $('#sidebar .list-group-item').removeClass('active');
        var $this = $('#btnSidebarBudget');
        if (!$this.hasClass('active')) {
            $this.addClass('active');
        }
        /* Highlight current sidebar item */
    });
</script>
{% endblock scripts %}

templates/budget/list-users.html
{% extends 'budget/base.html' %}
{% load static %}

{% block title %}
<title>Usuarios - DARAS </title>
{% endblock title %}


{% block content %}
<!-- Heading -->
<div class="row">
    <div class="col-12">
        <!-- Heading -->
        <div class="card mb-1 wow fadeIn">

            <!--Card content-->
            <div class="card-body d-sm-flex justify-content-between">

                <h6 class="mb-2 mb-sm-0 pt-1">
                    <span class="text-muted">Dashboard</span>
                    <span class="text-muted">/</span>
                    <span class="text-muted">Administración</span>
                    <span class="text-muted">/</span>
                    <span>Usuarios</span>
                </h6>

            </div>

        </div>
        <!-- Heading -->
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Usuarios registrados</h5>
                <small>Unicamente miembros del equipo de trabajo de DARAS</small>
                
                <table class="table table-stripped">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            
                            <th>
                                E-mail
                            </th>
                            <th>
                                Nombre
                            </th>
                            <th>
                                Apellidos
                            </th>
                            
                            {% if request.user.is_staff %}
                            <th>
                                Opciones
                            </th>
                            {% endif %}
                                
                            
                        </tr>
                    </thead>
                    <tbody>
                    {% for profile in daras_users %}
                        <tr>
                            <td>
                                {{forloop.counter}}
                            </td>
                            <td>
                                {{profile.user.username}}
                            </td>
                            <td>
                                {{profile.user.first_name}}
                            </td>
                            <td>
                                {{profile.user.last_name}}
                            </td>
                            
                            {% if request.user.is_staff %}
                            <td>
                                <a href="{% url 'budget:edit-daras-user' user_id=profile.user.id %}">
                                    Editar
                                </a>
                            </td>
                            {% endif %}
                                
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
{% endblock content %}